### ISSUE TITLE
Anvil duplicate

### ISSUE THREAD

**Issue by RubyTemple** [drew-mcbe/PocketMine-MP#10]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### OS and versions

* PocketMine-MP: 3.10.2
* PHP: 7.4
* Server OS: Ubuntu 18.04lts
* Game version: PE/Win10 

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

Video: https://vimeo.com/375161217

**Comment by Wumpotamus** [comment]
Anvils aren't implemented
